# This is a basic workflow that is manually triggered

name: Vector workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/code/pgvector_requirements.txt

      - name: Start PostgreSQL
        run: |
          docker run -d --name my_postgres -e POSTGRES_DB=vectordemo -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=password -p 5432:5432 -v ${{ github.workspace }}/SQL:/docker-entrypoint-initdb.d pgvector/pgvector:pg16

      - name: Run script
        run: |
          sleep 10  # wait for PostgreSQL to initialize
          python code/vector_demo.py --server localhost --database vectordemo --user dbuser --password password --file data/vector.json --output output.csv
          echo "----- CSV Report ------"
          cat output.csv
      
